name: Build UltraAppStudio ZIP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create project structure
        run: |
          # Build the entire project
          mkdir -p ultraappstudio/builder ai/models php/auth assets/css

          echo '<h1>UltraAppStudio</h1>' > ultraappstudio/index.html
          echo '<h2>Builder</h2>' > ultraappstudio/builder/index.html
          echo 'console.log("AI Ready");' > ultraappstudio/assets/js/ai.js
          echo 'body{font-family:sans-serif;}' > ultraappstudio/assets/css/style.css

          # Add AI scripts
          echo "from flask import Flask; app = Flask(__name__); @app.route('/'); def home(): return 'AI Running'; if __name__ == '__main__': app.run(port=5001)" > ultraappstudio/ai/server.py

          # Add build script
          echo "#!/bin/bash" > ultraappstudio/build.sh
          echo "zip -r ultraappstudio_full_build.zip ultraappstudio/" >> ultraappstudio/build.sh

      - name: Create ZIP
        run: |
          cd ultraappstudio
          zip -r ../ultraappstudio_full_build.zip .

      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ultraappstudio_full_build
          path: ultraappstudio_full_build.zip

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v1.0 \
            --repo ${{ github.repository }} \
            --title "UltraAppStudio AI Edition v1.0" \
            --notes "Auto-generated no-code SaaS builder with local AI." \
            ultraappstudio_full_build.zip
